/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Connectsql.connectionft;
import Control.qldiem_control;
import Model.cpasv;
import Model.diemsv;
import Model.ttsv;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.logging.Level;
import javax.swing.JFileChooser;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.View;
import javax.xml.datatype.DatatypeFactory;


/**
 *
 * @author TuanNguyen
 */
public class qldiem extends javax.swing.JFrame {

    /**
     * Creates new form qldiem
     */
    private Connection con;
    private PreparedStatement stmt;
    private ResultSet rs;

    public qldiem(ttsv getsv) {
        initComponents();
        //
        this.setTitle("Quản Lý Điểm Sinh Viên");
        //
        try {
            con = connectionft.getConnection();
        } catch (Exception e) {
        }
        //
        this.setLocationRelativeTo(null);
        thongtinsv.setText("----------------------------Thông Tin Sinh Viên----------------------------");
        masv.setText("Mã Sinh Viên : ");
        ma.setText(getsv.getMssv());
        ten.setText("Họ Và Tên : " + getsv.getName());
        ngaysinh.setText("Ngày Sinh : " + getsv.getDate());
        jLabel9.setText("Lớp : " + getsv.getClasssv());
        xinchao.setText("Xin Chào : " + getsv.getName());
        //
        showdiem();
    }

    public qldiem() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void showdiem() {
        //tao ten cot
        Vector cols = new Vector();
        cols.addElement("MSSV");
        cols.addElement("Kỳ Học");
        cols.addElement("Học Phần");
        cols.addElement("Tín Chỉ");
        cols.addElement("Hệ Số");
        cols.addElement("Giữa Kỳ");
        cols.addElement("Cuối Kỳ");
        cols.addElement("Điểm Chữ");
        //tao du lieu
        Vector data = new Vector();
        String sql = "select * from bangdiem where mssv=" + ma.getText() + "";
        try {
            stmt = con.prepareStatement(sql);
            //
            rs = stmt.executeQuery();
            //
            while (rs.next()) {
                Vector user = new Vector();
                user.addElement(rs.getString("mssv"));
                user.addElement(rs.getString("kyhoc"));
                user.addElement(rs.getString("hocphan"));
                user.addElement(rs.getInt("tinchi"));
                user.addElement(rs.getString("heso"));
                user.addElement(rs.getFloat("giuaky"));
                user.addElement(rs.getFloat("cuoiky"));
                user.addElement(rs.getString("diemchu"));
                data.add(user);
            }
        } catch (Exception e) {
        }
        bangdiemsv.setModel(new DefaultTableModel(data, cols));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tenhp = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gk = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ck = new javax.swing.JTextField();
        jLable5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        kyhoc = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        thongtinsv = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        heso = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        cpa = new javax.swing.JTextField();
        cpatheoky = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        gpa = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        hlsv = new javax.swing.JComboBox();
        gpadata = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        bangdiemsv = new javax.swing.JTable();
        xinchao = new javax.swing.JLabel();
        masv = new javax.swing.JLabel();
        ten = new javax.swing.JLabel();
        ngaysinh = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton10 = new javax.swing.JButton();
        ma = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Học Phần :");

        jLabel2.setText("Tín chỉ :");

        jLabel3.setText("Giữa Kỳ :");

        gk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gkActionPerformed(evt);
            }
        });

        jLabel4.setText("Cuối Kỳ :");

        jLable5.setText("Hệ Số :");

        jLabel6.setText("Kỳ Học :");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actions-edit-clear-icon.png"))); // NOI18N
        jButton1.setText("Clear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add-icon24x24.png"))); // NOI18N
        jButton2.setText("Thêm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        heso.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "7-3", "8-2" }));

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/edit-icon.png"))); // NOI18N
        jButton3.setText("Sửa");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Close-icon.png"))); // NOI18N
        jButton4.setText("Xóa");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("CPA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        cpatheoky.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "20141", "20142", "20143", "20151", "20152", "20153", "20161", "20162", "20163", "20171", "20172", "20173", "20181", "20182", "20183", "20191", "20192", "20193" }));

        jButton6.setText("GPA Cần");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("In");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Help-icon.png"))); // NOI18N
        jButton8.setText("Hdsd");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("GPA");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        hlsv.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Giỏi", "Khá", "Trung Bình" }));
        hlsv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hlsvActionPerformed(evt);
            }
        });

        bangdiemsv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5", "Title 6", "Title 7", "Title 8"
            }
        ));
        bangdiemsv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bangdiemsvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(bangdiemsv);

        jButton10.setText("Thoát");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(thongtinsv, javax.swing.GroupLayout.PREFERRED_SIZE, 604, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xinchao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton10))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(tenhp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(tc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jButton2)
                                .addGap(39, 39, 39)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(gk, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(ck, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLable5, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(heso, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(kyhoc, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton8)
                                .addGap(11, 11, 11)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cpatheoky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cpa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(82, 82, 82)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addComponent(hlsv, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gpadata, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)
                            .addComponent(ngaysinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(masv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(ten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(xinchao, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                        .addComponent(thongtinsv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(masv, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ma))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ten, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tenhp))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLable5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(heso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tc)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kyhoc)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(gk))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ck))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(cpatheoky, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6)
                    .addComponent(gpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gpadata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hlsv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {cpa, cpatheoky, gpa, gpadata, hlsv, jButton5, jButton6, jButton9});

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {ma, ten});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // lấy dữ liệu từ ô text về
        diemsv suadsv = new diemsv();
        suadsv.setMssv(ma.getText());
        suadsv.setKyhoc(kyhoc.getText());
        suadsv.setHocphan(tenhp.getText());
        suadsv.setTinchi(Float.parseFloat(tc.getText()));
        suadsv.setHeso(heso.getSelectedItem().toString());
        suadsv.setGiuaky(Float.parseFloat(gk.getText()));
        suadsv.setCuoiky(Float.parseFloat(ck.getText()));
        //sửa lại điểm chữ 
        float diemtongket;
        switch (suadsv.getHeso()) {
            case "7-3":
                //he so 7-3
                if (suadsv.getGiuaky() < 3.0 | suadsv.getCuoiky() < 3.0) {
                    suadsv.setDiemchu("F");
                } else {
                    
                    diemtongket = suadsv.getGiuaky() * 0.3f + suadsv.getCuoiky() * 0.7f;

                    if (diemtongket < 4.0) {
                        suadsv.setDiemchu("F");
                        break;
                    }
                    if (diemtongket >= 4.0 && diemtongket <= 4.9) {
                        suadsv.setDiemchu("D");
                        break;
                    }
                    if (diemtongket > 4.91 && diemtongket <= 5.4) {
                        suadsv.setDiemchu("D+");
                        break;
                    }
                    if (diemtongket > 5.41 && diemtongket <= 6.4) {
                        suadsv.setDiemchu("C");
                        break;
                    }
                    if (diemtongket > 6.41 && diemtongket <= 6.9) {
                        suadsv.setDiemchu("C+");
                        break;
                    }
                    if (diemtongket > 6.91 && diemtongket <= 7.9) {
                        suadsv.setDiemchu("B");
                        break;
                    }
                    if (diemtongket > 7.91 && diemtongket <= 8.4) {
                        suadsv.setDiemchu("B+");
                        break;
                    }
                    if (diemtongket > 8.41 && diemtongket <= 9.4) {
                        suadsv.setDiemchu("A");
                        break;
                    }
                    if (diemtongket > 9.41 && diemtongket <= 10.0) {
                        suadsv.setDiemchu("A+");
                        break;
                    }
                }

            //
            case "8-2":
                // he so 8-2
                if (suadsv.getGiuaky() < 3.0 | suadsv.getCuoiky() < 3.0) {
                    suadsv.setDiemchu("F");
                } else {
                    diemtongket = suadsv.getGiuaky() * 0.2f + suadsv.getCuoiky() * 0.8f;

                    if (diemtongket < 4.0) {
                        suadsv.setDiemchu("F");
                        break;
                    }
                    if (suadsv.getGiuaky() < 3.0) {
                        suadsv.setDiemchu("F");
                        break;
                    }
                    if (suadsv.getCuoiky() < 3.0) {
                        suadsv.setDiemchu("F");
                        break;
                    }
                    if (diemtongket >= 4.0 && diemtongket <= 4.9) {
                        suadsv.setDiemchu("D");
                        break;
                    }
                    if (diemtongket > 4.91 && diemtongket <= 5.4) {
                        suadsv.setDiemchu("D+");
                        break;
                    }
                    if (diemtongket > 5.41 && diemtongket <= 6.4) {
                        suadsv.setDiemchu("C");
                        break;
                    }
                    if (diemtongket > 6.41 && diemtongket <= 6.9) {
                        suadsv.setDiemchu("C+");
                        break;
                    }
                    if (diemtongket > 6.91 && diemtongket <= 7.9) {
                        suadsv.setDiemchu("B");
                        break;
                    }
                    if (diemtongket > 7.91 && diemtongket <= 8.4) {
                        suadsv.setDiemchu("B+");
                        break;
                    }
                    if (diemtongket > 8.41 && diemtongket <= 9.4) {
                        suadsv.setDiemchu("A");
                        break;
                    }
                    if (diemtongket > 9.41 && diemtongket <= 10.0) {
                        suadsv.setDiemchu("A+");
                        break;
                    }
                }
        }
        qldiem_control b = new qldiem_control();
        b.suadiem(suadsv);
        //
        showdiem();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        diemsv xoadsv = new diemsv();
        xoadsv.setHocphan(tenhp.getText().trim());
        xoadsv.setKyhoc(kyhoc.getText().trim());
        //
        qldiem_control c = new qldiem_control();
        c.xoadiem(xoadsv);
        //
        showdiem();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void hlsvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hlsvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hlsvActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        cpasv dgpa = new cpasv();
        //
        qldiem_control a = new qldiem_control();
        a.gpa(dgpa);
        //
        gpa.setText(String.valueOf(dgpa.getGpa()));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        this.setVisible(false);
        login_view a = new login_view();
        a.setVisible(true);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // lấy điêm từ ô text về
        diemsv dsv = new diemsv();
        dsv.setMssv(ma.getText());
        dsv.setKyhoc(kyhoc.getText());
        dsv.setHocphan(tenhp.getText());
        dsv.setTinchi(Integer.parseInt(tc.getText()));
        dsv.setHeso(heso.getSelectedItem().toString());
        dsv.setGiuaky(Float.parseFloat(gk.getText()));
        dsv.setCuoiky(Float.parseFloat(ck.getText()));
        //
        float diemtongket;
        switch (heso.getSelectedItem().toString()) {
            case "7-3":
                //he so 7-3
                if (dsv.getGiuaky() < 3.0 | dsv.getCuoiky() < 3.0) {
                    dsv.setDiemchu("F");
                } else {
                    diemtongket = dsv.getGiuaky() * 0.3f + dsv.getCuoiky() * 0.7f;

                    if (diemtongket < 4.0) {
                        dsv.setDiemchu("F");
                        break;
                    }
                    if (diemtongket >= 4.0 && diemtongket <= 4.9) {
                        dsv.setDiemchu("D");
                        break;
                    }
                    if (diemtongket > 4.91 && diemtongket <= 5.4) {
                        dsv.setDiemchu("D+");
                        break;
                    }
                    if (diemtongket > 5.41 && diemtongket <= 6.4) {
                        dsv.setDiemchu("C");
                        break;
                    }
                    if (diemtongket > 6.41 && diemtongket <= 6.9) {
                        dsv.setDiemchu("C+");
                        break;
                    }
                    if (diemtongket > 6.91 && diemtongket <= 7.9) {
                        dsv.setDiemchu("B");
                        break;
                    }
                    if (diemtongket > 7.91 && diemtongket <= 8.4) {
                        dsv.setDiemchu("B+");
                        break;
                    }
                    if (diemtongket > 8.41 && diemtongket <= 9.4) {
                        dsv.setDiemchu("A");
                        break;
                    }
                    if (diemtongket > 9.41 && diemtongket <= 10.0) {
                        dsv.setDiemchu("A+");
                        break;
                    }
                }

            //
            case "8-2":
                // he so 8-2
                if (dsv.getGiuaky() < 3.0 | dsv.getCuoiky() < 3.0) {
                    dsv.setDiemchu("F");
                } else {
                    diemtongket = dsv.getGiuaky() * 0.2f + dsv.getCuoiky() * 0.8f;
                    //
                    if (diemtongket < 4.0) {
                        dsv.setDiemchu("F");
                        break;
                    }
                    if (diemtongket >= 4.0 && diemtongket <= 4.9) {
                        dsv.setDiemchu("D");
                        break;
                    }
                    if (diemtongket > 4.91 && diemtongket <= 5.4) {
                        dsv.setDiemchu("D+");
                        break;
                    }
                    if (diemtongket > 5.41 && diemtongket <= 6.4) {
                        dsv.setDiemchu("C");
                        break;
                    }
                    if (diemtongket > 6.41 && diemtongket <= 6.9) {
                        dsv.setDiemchu("C+");
                        break;
                    }
                    if (diemtongket > 6.91 && diemtongket <= 7.9) {
                        dsv.setDiemchu("B");
                        break;
                    }
                    if (diemtongket > 7.91 && diemtongket <= 8.4) {
                        dsv.setDiemchu("B+");
                        break;
                    }
                    if (diemtongket > 8.41 && diemtongket <= 9.4) {
                        dsv.setDiemchu("A");
                        break;
                    }
                    if (diemtongket > 9.41 && diemtongket <= 10.0) {
                        dsv.setDiemchu("A+");
                        break;
                    }
                }
        }

        qldiem_control diem = new qldiem_control();
        diem.themdiem(dsv);
        showdiem();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void gkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gkActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        tenhp.setText(null);
        gk.setText(null);
        ck.setText(null);
        tc.setText(null);
        kyhoc.setText(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

    }//GEN-LAST:event_jButton3MouseClicked

    private void bangdiemsvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangdiemsvMouseClicked
        int row = bangdiemsv.getSelectedRow();
        if (row != -1) {
            kyhoc.setText(bangdiemsv.getValueAt(row, 1).toString());
            tenhp.setText(bangdiemsv.getValueAt(row, 2).toString());
            tc.setText(bangdiemsv.getValueAt(row, 3).toString());
            heso.setSelectedItem(bangdiemsv.getValueAt(row, 4).toString());
            gk.setText(bangdiemsv.getValueAt(row, 5).toString());
            ck.setText(bangdiemsv.getValueAt(row, 6).toString());
        }
    }//GEN-LAST:event_bangdiemsvMouseClicked

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        hdsd a = new hdsd();
        a.setVisible(true);
        a.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
//        int a = 0;
//        JFileChooser chooser = new JFileChooser();
//        int i = chooser.showSaveDialog(chooser);
//        if (i == JFileChooser.APPROVE_OPTION) {
//            File file = chooser.getSelectedFile();
//            try {
//                WritableWorkbook wb = Workbook.createWorkbook(file);
//                WritableSheet st = wb.createSheet("Report", 0);
//                //
//                st.addCell(new Label(0, 0, "Bảng Điểm Sinh Viên " + ma.getText() + ""));
//                //
//                DefaultTableModel bangdiem = (DefaultTableModel) bangdiemsv.getModel();
//                //Lưu dữ liệu bảng vào mảng data[]
//                int number = bangdiemsv.getRowCount() * bangdiemsv.getColumnCount();
//                String data[] = new String[number];
//                for (int j = 0; j < bangdiemsv.getRowCount(); j++) {
//                    for (int k = 0; k < bangdiemsv.getColumnCount(); k++) {
//                        data[a] = (String) String.valueOf(bangdiemsv.getValueAt(j, k));
//                        a++;
//                    }
//                }
//                a = 0;
//                //Ghi dữ liệu mảng data[] vào file
//                for (int j = 2; j < bangdiemsv.getRowCount() + 2; j++) {
//                    for (int k = 0; k < bangdiemsv.getColumnCount(); k++) {
//                        st.addCell(new Label(k, j, data[a]));
//                        a++;
//                    }
//                }
//                wb.write();
//                //
//                wb.close();
//                //              
//                JOptionPane.showMessageDialog(null, "Lưu file thành công!");
//            } catch (Exception e2) {
//                JOptionPane.showMessageDialog(null, "Lỗi khi lưu file!");
//            }
//        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        cpasv dcpa = new cpasv();
        dcpa.setKyhoc(cpatheoky.getSelectedItem().toString());
        //
        qldiem_control tinhcpa = new qldiem_control();
        tinhcpa.cpa(dcpa);
        //
        cpa.setText(String.valueOf(dcpa.getCpa()));
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        cpasv a = new cpasv();
        a.setHlsv(hlsv.getSelectedItem().toString());
        //
        qldiem_control b = new qldiem_control();
        b.gpacan(a);
        gpadata.setText(">="+ String.valueOf(a.getGpacan()));
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qldiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qldiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qldiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qldiem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                } catch (InstantiationException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                } catch (UnsupportedLookAndFeelException ex) {
                    Logger.getLogger(View.class.getName()).log(Level.SEVERE, null, ex);
                }
                new qldiem(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangdiemsv;
    private javax.swing.JTextField ck;
    private javax.swing.JTextField cpa;
    private javax.swing.JComboBox cpatheoky;
    private javax.swing.JTextField gk;
    private javax.swing.JTextField gpa;
    private javax.swing.JTextField gpadata;
    private javax.swing.JComboBox heso;
    private javax.swing.JComboBox hlsv;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLable5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kyhoc;
    private javax.swing.JLabel ma;
    private javax.swing.JLabel masv;
    private javax.swing.JLabel ngaysinh;
    private javax.swing.JTextField tc;
    private javax.swing.JLabel ten;
    private javax.swing.JTextField tenhp;
    private javax.swing.JLabel thongtinsv;
    private javax.swing.JLabel xinchao;
    // End of variables declaration//GEN-END:variables
}
